[package]
name = "server-tui"
version = "0.1.1"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = { version = "0.29.0", features = [ "unstable-widget-ref" ] }
sysinfo = "0.32.0"
systemctl = "0.4.0"
systemd = "0.10.0"
